categories:
  - title: ":boom: Breaking Changes"
    label: "breaking"
  - title: ":rocket: Features"
    label: "enhancement"
  - title: ":fire: Removals and Deprecations"
    label: "removal"
  - title: ":beetle: Fixes"
    label: "bug"
  - title: ":racehorse: Performance"
    label: "performance"
  - title: ":rotating_light: Testing"
    label: "testing"
  - title: ":construction_worker: Continuous Integration"
    label: "ci"
  - title: ":books: Documentation"
    label: "documentation"
  - title: ":hammer: Refactoring"
    label: "refactoring"
  - title: ":lipstick: Style"
    label: "style"
  - title: ":package: Dependencies"
    labels:
      - "dependencies"
      - "build"
header: |
  If your inverter is not running the latest manager version, you may need to select your manager version in the integration settings. See [the wiki](https://github.com/nathanmarlor/foxess_modbus/wiki/Supported-Versions) for details.

  | Inverter | Supported by default | Selectable in settings |
  |---|---|---|
  | H1 G1 / AC1 / AIO | All | |
  | H1 G2 | v1.44 | All |
  | H3 | v1.80 | All |
  | AIO-H3 | v1.01 | All |
  | H3 Pro | v1.22 | All |
  | KH / KA | v1.33 | All |
template: |
  ## Changes

  $CHANGES
