repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^custom_components\/foxess_modbus\/vendor
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.4
    hooks:
      - id: ruff
      - id: ruff-format
        args: [--check]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        args: [--show-traceback]
        # These are duplicated from requirements.txt
        additional_dependencies:
          [
            homeassistant-stubs==2025.1.1,
            types-python-slugify==8.0.0.2,
            voluptuous-stubs==0.1.1,
          ]
